
global:
  tracer:
    zipkin:
      address: aspen-mesh-jaeger-collector.istio-system:9411
  certificateCustomFields: true
jaeger:
  enabled: true
meshConfig:
  accessLogFile: /dev/stdout
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
gateways:
  istio-egressgateway:
    replicaCount: 1
    autoscaleEnabled: false
    autoscaleMin: 1
    autoscaleMax: 1
    ports: 
    - port: 80 
      targetPort: 8080 
      name: http2 
      protocol: TCP 
    - port: 443 
      name: https 
      targetPort: 8443 
      protocol: TCP 
    - port: 15443 
      targetPort: 15443 
      name: tls 
      protocol: TCP 
    - port: 5672 
      targetPort: 5672 
      name: rabbitmq 
      protocol: TCP
    - port: 5671
      targetPort: 5671
      name: rabbitmq-tls
      protocol: TCP
