
# Set automated workload entry creation
pilot:
  env:
    PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
    PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS: true
meshConfig:
  defaultConfig:
    proxyMetadata: {}
