apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "name=kiali"
  labels:
    app: kiali
  name: kiali-lb
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 20001
    protocol: TCP
    targetPort: 20001
  selector:
    app: kiali
  type: LoadBalancer
